name: connector_icons
description: EV Connector Icons
version: 0.0.2

environment:
  sdk: ^3.5.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^5.0.0

flutter:

  fonts:
    - family: Connector
      fonts:
        - asset: assets/fonts/Connector.ttf