/// Flutter icons Connector
/// Copyright (C) 2024 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.

library;

import 'package:flutter/widgets.dart';

class ConnectorIcons {
  ConnectorIcons._();

  static const String _kFontFam = 'Connector';
  static const String _kFontPkg = 'connector_icons';

  static const IconData nacs = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData type_1 = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData type_2 = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ccs = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chademo = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gbt = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
